### ISSUE TITLE
unable to access v2raya 

### ISSUE THREAD

**Issue by latiefkhan** [helmiau/HelmiWrt-OS#28]

**Comment by helmiau** [comment]
Already fixed by 2018.09.03 build's

**Comment by latiefkhan** [comment]
i have been installed a new release but did nothing fix v2raya, still not accessible

**Comment by malikshi** [comment]
recommend to access ip lan openwrt with port 2017.

**Comment by helmiau** [comment]
> i have been installed a new release but did nothing fix v2raya, still not accessible
luci-app-v2raya removed, this is the best solution for now.
